// APP
export const SWITCH_CHANNELS_PANEL = 'SWITCH_CHANNELS_PANEL'

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const TOOGLE_AUTH_FORM = 'TOOGLE_AUTH_FORM'
export const SET_AUTH_MESSAGE = 'SET_AUTH_MESSAGE'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'

// USERS
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const SET_USER_SOCKET_ID = 'SET_USER_SOCKET_ID'

// SERVERS
export const SWITCH_SERVERS = 'SWITCH_SERVERS'
export const EMPTY_SERVER_LIST = 'EMPTY_SERVER_LIST'
export const EMPTY_CHANNEL_LIST = 'EMPTY_CHANNEL_LIST'
export const RESET_ACTIVE_SERVER = 'RESET_ACTIVE_SERVER'
export const INSTANTIATE_CHANNELS = 'INSTANTIATE_CHANNELS'
export const FETCH_SERVER_SUCCESS = 'FETCH_SERVER_SUCCESS'
export const FETCH_SERVER_FAILURE = 'FETCH_SERVER_FAILURE'
export const FETCH_SERVERS_SUCCESS = 'FETCH_SERVERS_SUCCESS'
export const FETCH_SERVERS_FAILURE = 'FETCH_SERVERS_FAILURE'
export const CONNECT_TO_SOCKET_SERVER = 'CONNECT_TO_SOCKET_SERVER'
export const DISCONNECT_FROM_SOCKET_SERVER = 'DISCONNECT_FROM_SOCKET_SERVER'

// CHANNELS
