// APP
export const SHOW_CONTACTS_PANEL = 'SHOW_CONTACTS_PANEL'

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const TOOGLE_AUTH_FORM = 'TOOGLE_AUTH_FORM'
export const SET_AUTH_MESSAGE = 'SET_AUTH_MESSAGE'
export const REGISTARTION_SUCCESS = 'REGISTARTION_SUCCESS'
export const REGISTARTION_FAILURE = 'REGISTARTION_FAILURE'

// USERS
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

// SERVERS
export const SWITCH_SERVERS = 'SWITCH_SERVERS'
export const RESET_SERVER_LIST = 'RESET_SERVER_LIST'
export const EMPTY_SERVER_CHANNELS = 'EMPTY_SERVER_CHANNELS'
export const RETRIEVE_SERVERS_LIST = 'RETRIEVE_SERVERS_LIST'
export const RETRIEVE_SERVER_CHANNELS = 'RETRIEVE_SERVER_CHANNELS'