// APP
export const SET_SHOW_CONTACTS_PANEL = 'TOGGLE_SHOW_CONTACTS_PANEL'

// AUTH
export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_AUTH_MESSAGE = 'SET_AUTH_MESSAGE'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const DESTROY_ACCESS_TOKEN = 'DESTROY_ACCESS_TOKEN'
export const TOGGLE_IS_REGISTERING = 'TOGGLE_IS_REGISTERING'

// USERS


// SERVERS
export const SWITCH_SERVERS = 'SWITCH_SERVERS'
export const RESET_SERVER_LIST = 'RESET_SERVER_LIST'
export const EMPTY_SERVER_CHANNELS = 'EMPTY_SERVER_CHANNELS'
export const RETRIEVE_SERVERS_LIST = 'RETRIEVE_SERVERS_LIST'
export const RETRIEVE_SERVER_CHANNELS = 'RETRIEVE_SERVER_CHANNELS'